### PR TITLE
PlayerPreview pull with GuiChatPatch updated

### PR DESCRIPTION
**Pull request by cookiedragon234**
Dan merged my PR prematurely, so can we keep this open so that we can discuss code and get it all good before its merged? Thanks.

Ive added the guichat patch so far which allows opening guis on hack/command toggle.

### CODE REVIEW

**Comment by famous1622** [comment]
You generally PR after you're ready for a pull. It's a request to pull/for comments before the pull.

**Comment by cookiedragon234** [comment]
@ethug mind elaborating? What do you mean “no longer able to work”? does it crash?

**Comment by ethug** [comment]
Apologies, the HUD ceases to work beyond binding and pressing that key.  Have you tested this?  I've built 3 different times and still the same issue, switched back to a build of the latest Seppuku master branch and everything worked fine.

**Comment by cookiedragon234** [comment]
I had not tested binding, the purpose of this patch was to focus on toggling through commands, I’ll take a look.

**Comment by jvyden420** [comment]
> Dan merged my PR prematurely

Do what I do and put [WIP] in the title, or use draft pull requests when making the PR.

**Comment by ethug** [comment]
> 
> 
> > Dan merged my PR prematurely
> 
> Do what I do and put [WIP] in the title, or use draft pull requests when making the PR.

That wasn't the issue, I had changed remotes without thinking about file conflicts and had updated some other file.

On a side note, please DO NOT make pull requests with the WIP title as an alternative.  Handling pull requests properly makes it infinitely easier on myself so I can determine when an in-depth review is necessary.  You should not be opening pull requests to master branches with untested/experimental code.

Side rant:  the majority of pull requests so far have been unknowingly broken or not working as intended.  Please take the time to test your code against a variety of test cases so I won't need to spend as much time reviewing code and your features can be merged into Seppuku much more quickly.

**Comment by ethug** [comment]
It is now apparent due to recent events elsewhere this will not be fixed.  This will have to be done at some point on by another.

**Pull request closed without merging**
